# Renders template.qmd on GitHub Actions and deploys it on GitHub Pages to provide a sample view of the template

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths
on:
  push:
    branches: main
    paths:
      - '_extensions/**'
      - '**.qmd'
      - '**.yml'

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
        # with:
          # r-version: '4.2.0' # The R version to download (if necessary) and use.
      
      # https://github.com/r-lib/actions/tree/v2-branch/setup-r-dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown
            any::tidyverse
            any::paletteer
        
        # https://github.com/quarto-dev/quarto-actions/tree/main/setup
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # with:
          # version: SPECIFIC-QUARTO-VERSION-HERE
          # To install LaTeX to build PDF book 
          # tinytex: true 
          # uncomment below and fill to pin a version
      
      # add software dependencies here

      # https://github.com/quarto-dev/quarto-actions/tree/main/publish#github-pages
      # -> Notice specific setup!
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: template.qmd
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

